/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author anna
 */
public class CreateTest2 extends javax.swing.JFrame {

    static byte[] img = null;
    //o arithmos ths kathe erwthshs ,m auto pernaw apo to ena frame sto epomeno h k sto prohgoumeno
    static int counterq = 1;
     static int counterl = 1;
     //metrhths posa item exei to list gia na emfanizw to end test mono sto telos
     //den xreiasthke telika..
     static int count = 1;
    
    String s = null;
    
    
    static int t_id;
    static String testname;
    static double rate = 0;
    static int allow_attempts = 1;
    String textArea;
    File image;
    String textField1;
    String textField2;
    String textField3;
    String textField4;
    String textField5;
    
    byte[] im = null;
    
    //metrhths gia to an patithike to attach gia image, an den tha pernaei sta next question k end test default path sto s
    int imagePassed = 0;
  
    //static ArrayList<CreateTest2> list = new ArrayList<CreateTest2>();
    static CreateTest2[] list;
    
    /**
     * Creates new form CreateTest2
     */
    public CreateTest2() {
        initComponents();
        //an dld einai h ewrthsh 1 (counterq ==1) tote na mhh fainetai to button back gia na mhn to pataei o user
        if (counterq < 2) {
            back.setVisible(false);
        }
        //gia na blepei o user panw sto frame (p.x puestion 2)
        String q = Integer.toString(counterq);
        jLabel2.setText(q);
        
        Role r = new Role();
        r.getBackgroundImage();
        img = r.im;
        ImageIcon image = new ImageIcon(img); 
        Image nim =  image.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel5.setIcon(image);
         
    }
    //to krataw epd to xrhsimopoiw sto TeacherViewTest
    public CreateTest2(String textfield, int id) {
        initComponents();
        t_id = id;
        if (counterq < 2) {
            back.setVisible(false);
        }
        list = new CreateTest2[counterq+1];
        
        testname= textfield;
        
        String q = Integer.toString(counterq);
        jLabel2.setText(q);
        
        Role r = new Role();
        r.getBackgroundImage();
        img = r.im;
        ImageIcon image = new ImageIcon(img); 
        Image nim =  image.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel5.setIcon(image);
    }
    
    //pernaw apto nameTest to onoma tou test to id tou kathighth, thn arnhtikh bathmologhsh(an den peiraxtei einai default 0)
    //k tis prospatheies pou epitrepontai (an den ppeiraxtei default 1 prosaptheia)
     public CreateTest2(String textfield, int id, double r, int allow_atts) {
        initComponents();
        t_id = id;
        rate = r;
        allow_attempts = allow_atts;
        if (counterq < 2) {
            back.setVisible(false);
        }
        list = new CreateTest2[counterq+1];
        
        testname= textfield;
        
        String q = Integer.toString(counterq);
        jLabel2.setText(q);
        
        Role re = new Role();
        re.getBackgroundImage();
        img = re.im;
        ImageIcon image = new ImageIcon(img); 
        Image nim =  image.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel5.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel_image = new javax.swing.JLabel();
        jButton_attachimage = new javax.swing.JButton();
        back = new javax.swing.JButton();
        endTest = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(678, 558));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ερώτηση");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 82, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 20, 66, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(47, 53, 550, 79);

        jLabel_image.setText("icon");
        getContentPane().add(jLabel_image);
        jLabel_image.setBounds(299, 148, 160, 83);

        jButton_attachimage.setText("Εισαγωγή Εικόνας");
        jButton_attachimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_attachimageActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_attachimage);
        jButton_attachimage.setBounds(350, 242, 180, 23);

        back.setText("Προηγούμενη ερώτηση");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(103, 424, 180, 23);

        endTest.setText("Τέλος και αποθήκευση");
        endTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTestActionPerformed(evt);
            }
        });
        getContentPane().add(endTest);
        endTest.setBounds(470, 424, 170, 23);

        next.setText("Επόμενη ερώτηση");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(300, 424, 160, 23);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Δώσε αριθμό σωστής ερώτησης (1-4)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 396, 230, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 275, 590, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(10, 302, 590, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(10, 328, 590, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(10, 354, 590, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(255, 393, 110, 20);

        exit.setText("Έξοδος");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(7, 424, 90, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 730, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        //to kanw not visible etsi wste se kathe back na nai pleon not visible, gia na ginetai end test mono sth teleutaia erwthsh
            endTest.setVisible(false);
        
        
        counterl++;
        //το κανω αυτο για να μεγαλωνω το μεγεθος της list.
        CreateTest2[] list2 = new CreateTest2[counterl+1];
        for (int i = 0; i < list.length; i++) {
            if(list[i] != null) {
            list2[i] = list[i];
            }
            }
        list = new CreateTest2[counterl+1];
         for (int i = 0; i < list2.length; i++) {
             if(list2[i] != null) {
            list[i] = list2[i];
             }
        }
        
        //if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()) {
        if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() ||  jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Υπάρχουν κενά πεδία, συμπλήρωσε όλα τα πεδία,(το λιγότερο 2 απαντήσεις πρεπει να δοθούν)");
       
        } else if(!jTextField5.getText().toString().equals("1") && !jTextField5.getText().toString().equals("2") && !jTextField5.getText().toString().equals("3") && !jTextField5.getText().toString().equals("4")) {  
        
            JOptionPane.showMessageDialog(null, "το πεδίο της σωστής απάντησης πρέπει να είναι μεταξύ 1-4");
        }
        else {
        
        //if (list.get(counterq-1).equals(null)) {
        if (list[counterq-1] == null) {
            
        textArea = jTextArea1.getText();
        textField1 = jTextField1.getText();
        textField2 = jTextField2.getText();
        textField3 = jTextField3.getText();
        textField4 = jTextField4.getText();
        textField5 = jTextField5.getText();
        list[counterq-1] = this;
        count++;
        this.dispose();
        //counterl++;
        } else{
             
        list[counterq-1].textArea = jTextArea1.getText();
        
        list[counterq-1].textField1 = jTextField1.getText();
        list[counterq-1].textField2 = jTextField2.getText();
        list[counterq-1].textField3 = jTextField3.getText();
        list[counterq-1].textField4 = jTextField4.getText();
        list[counterq-1].textField5 = jTextField5.getText();
        this.dispose();
        }
        
        //if (list.get(counterq).equals(null)) {
        if (list[counterq] == null) {
            counterq++;
            CreateTest2 ct2 = new CreateTest2();
            ct2.setVisible(true);
            ct2.setResizable(false);
        } else {
            
            CreateTest2 ct = list[counterq];
            ct.setVisible(true);
            ct.setResizable(false);
            counterq++;
        }
    }//GEN-LAST:event_nextActionPerformed
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        counterl++;
        CreateTest2[] list2 = new CreateTest2[counterl+1];
        for (int i = 0; i < list.length; i++) {
            if(list[i] != null) {
            list2[i] = list[i];
            }
        }
        list = new CreateTest2[counterl+1];
         for (int i = 0; i < list2.length; i++) {
             if(list2[i] != null) {
            list[i] = list2[i];
             }
        }
        
        //if (list.get(counterq-1).equals(null)) {
         if (list[counterq-1] == null) {
             
        textArea = jTextArea1.getText();
        textField1 = jTextField1.getText();
        textField2 = jTextField2.getText();
        textField3 = jTextField3.getText();
        textField4 = jTextField4.getText();
        textField5 = jTextField5.getText();
        list[counterq-1] = this;
        count++;
        this.dispose();
        //counterl++;
        } else{
            
        list[counterq-1].textArea = jTextArea1.getText();
        
        list[counterq-1].textField1 = jTextField1.getText();
        list[counterq-1].textField2 = jTextField2.getText();
        list[counterq-1].textField3 = jTextField3.getText();
        list[counterq-1].textField4 = jTextField4.getText();
        list[counterq-1].textField5 = jTextField5.getText();
        this.dispose();
        }
        counterq--;
        list[counterq-1].setVisible(true);
        list[counterq-1].setResizable(false);
    }//GEN-LAST:event_backActionPerformed

    private void jButton_attachimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_attachimageActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
         chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE","jpeg","gif","png");
         chooser.addChoosableFileFilter(filter);
         int result = chooser.showSaveDialog(null);
         if (result == JFileChooser.APPROVE_OPTION) {
             imagePassed++;
             File selectedFile = chooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             jLabel_image.setIcon(ResizeImage(path));
             s = path;
             System.out.println(s);
         } 
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("καθόλου δεδομένα");
         }
         //imagePassed++;
    }//GEN-LAST:event_jButton_attachimageActionPerformed

    private void endTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTestActionPerformed
        // TODO add your handling code here:
        
         counterl++;
        CreateTest2[] list2 = new CreateTest2[counterl+1];
        for (int i = 0; i < list.length; i++) {
            if(list[i] != null) {
            list2[i] = list[i];
            }
            }
        list = new CreateTest2[counterl+1];
         for (int i = 0; i < list2.length; i++) {
             if(list2[i] != null) {
            list[i] = list2[i];
             }
        }
        
        //if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()) {
        if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Υπάρχουν κενά πεδία, συμπλήρωσε όλα τα πεδία,(το λιγότερο 2 απαντήσεις πρεπει να δοθούν)");
        
        } else if(!jTextField5.getText().toString().equals("1") && !jTextField5.getText().toString().equals("2") && !jTextField5.getText().toString().equals("3") && !jTextField5.getText().toString().equals("4")) {  
        
            JOptionPane.showMessageDialog(null, "το πεδίο της σωστής απάντησης πρέπει να είναι μεταξύ 1-4");
        }
        else {
       
        if (list[counterq-1] == null) {
            
        textArea = jTextArea1.getText();
        textField1 = jTextField1.getText();
        textField2 = jTextField2.getText();
        textField3 = jTextField3.getText();
        textField4 = jTextField4.getText();
        textField5 = jTextField5.getText();
        list[counterq-1] = this;
        this.dispose();
        //counterl++;
        } else{
             
        list[counterq-1].textArea = jTextArea1.getText();
        
        list[counterq-1].textField1 = jTextField1.getText();
        list[counterq-1].textField2 = jTextField2.getText();
        list[counterq-1].textField3 = jTextField3.getText();
        list[counterq-1].textField4 = jTextField4.getText();
        list[counterq-1].textField5 = jTextField5.getText();
        this.dispose();
        }
       
       for (int i=0; i<counterq; i++) {
           int no = i +1;
           String tname = list[i].testname;
           String ta = list[i].textArea;
           String tf1 =  list[i].textField1;
           String tf2 = list[i].textField2;
           String tf3 = list[i].textField3;
           String tf4 = list[i].textField4;
           String tf5 = list[i].textField5;
           
             int ans = 0;
           ans = Integer.parseInt(tf5);
           
           
           try {
                if (list[i].imagePassed > 0) {
                    
               InputStream is = new FileInputStream(new File(list[i].s));
               theQuery4(t_id,tname,no,ta,tf1,tf2,tf3,tf4,ans, is);
                } else {
                   
                    //list[i].s = "C:"+"\\"+"Users"+"\\"+"anna"+"\\"+"Documents"+"\\"+"NetBeansProjects"+"\\"+"quiz"+"\\"+"src"+"\\"+"quiz"+"\\"+"test.jpg";
                    
                    //File file = new File("src\\quiz\\test.png");  swsto!
                    //String path = file.getAbsolutePath();  swsto!
                    //list[i].s = path;  swsto!
                    
                    getIamgeTest();
                    theQuery5(t_id,tname,no,ta,tf1,tf2,tf3,tf4,ans, im);
                    //InputStream is = new FileInputStream(new File(list[i].s)); swsto!
                    //InputStream is = new FileInputStream(new File(path));
                   
                   
                    //theQuery4(t_id,tname,no,ta,tf1,tf2,tf3,tf4,ans, is); swsto!
                    
                }
                
                
           } catch (FileNotFoundException ex) {
               Logger.getLogger(CreateTest.class.getName()).log(Level.SEVERE, null, ex);
           }
           
            }
            insertTTeacher(t_id,testname,rate,allow_attempts);
       
           PublishTest pt = new PublishTest(t_id, testname);
           pt.setVisible(true);
           pt.setResizable(false);

           counterq = 1;
           counterl = 1;
           s = null;
           testname = null;
           list = null;
           rate = 0;
           allow_attempts = 1;
           
           //Teacher t = new Teacher();
           //t.setVisible(true);
           
        }  
    }//GEN-LAST:event_endTestActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        counterq = 1;
        counterl = 1;
        testname = null;
        rate = 0;
        allow_attempts = 1;
        list = null;
        this.dispose();
        Teacher t = new Teacher(t_id);
        t.setVisible(true);
        t.setResizable(false);
    }//GEN-LAST:event_exitActionPerformed
     
    public void theQuery4(int id,String tname, int n, String t1, String rb1, String rb2, String rb3, String rb4, int ra, InputStream is) {
        
        Connection con = null;
        
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            //PreparedStatement ps = con.prepareStatement("insert into question2 (testname,No,texta,rbutton1,rbutton2,rbutton3,rbutton4,n_of_ran,image) values (?,?,?,?,?,?,?,?,?)");
           PreparedStatement ps = con.prepareStatement("insert into question2 (id_teacher,testname,No,texta,rbutton1,rbutton2,rbutton3,rbutton4,n_of_ran,image) values (?,?,?,?,?,?,?,?,?,?)");
            //InputStream is = new FileInputStream(new File(s));
             ps.setInt(1, id);
            ps.setString(2, tname);
            ps.setInt(3, n);
            ps.setString(4, t1);
            ps.setString(5, rb1);
            ps.setString(6, rb2);
            ps.setString(7, rb3);
            ps.setString(8, rb4);
            ps.setInt(9, ra);
            ps.setBlob(10, is);
            ps.executeUpdate();
 
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }
    
    public void theQuery5(int id,String tname, int n, String t1, String rb1, String rb2, String rb3, String rb4, int ra, byte[] b) {
        
        Connection con = null;
        
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            //PreparedStatement ps = con.prepareStatement("insert into question2 (testname,No,texta,rbutton1,rbutton2,rbutton3,rbutton4,n_of_ran,image) values (?,?,?,?,?,?,?,?,?)");
           PreparedStatement ps = con.prepareStatement("insert into question2 (id_teacher,testname,No,texta,rbutton1,rbutton2,rbutton3,rbutton4,n_of_ran,image) values (?,?,?,?,?,?,?,?,?,?)");
            //InputStream is = new FileInputStream(new File(s));
             ps.setInt(1, id);
            ps.setString(2, tname);
            ps.setInt(3, n);
            ps.setString(4, t1);
            ps.setString(5, rb1);
            ps.setString(6, rb2);
            ps.setString(7, rb3);
            ps.setString(8, rb4);
            ps.setInt(9, ra);
            ps.setBinaryStream(10, new ByteArrayInputStream(b), b.length);
            ps.executeUpdate();
 
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }
    
    public void insertTTeacher (int id, String tname, double rate, int allow_atts) {
        
        Connection con = null;
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            PreparedStatement ps = con.prepareStatement("insert into test_teacher (id_teacher,testname,neg_rate,allow_attempts,published) values (?,?,?,?,?)"); 
            ps.setInt(1, id);
            ps.setString(2, tname);
            ps.setDouble(3, rate);
            ps.setInt(4, allow_atts);
            ps.setInt(5, 0);
            ps.executeUpdate();
             JOptionPane.showMessageDialog(null, "Τα δεδομένα κατοχυρώθηκαν");
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }  
        
    }
    
    
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
     
    private void getIamgeTest() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select test from images";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            im = rs.getBytes("test");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton endTest;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton_attachimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
