/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;


import java.awt.Image;
import java.beans.XMLDecoder;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author anna
 */
public class CreateTest extends javax.swing.JFrame {

    /**
     * Creates new form CreateTest
     */
    static int counterq = 0;
    
    String s = null;
    
    static String testname;
    String textArea;
    File image;
    String textField1;
    String textField2;
    String textField3;
    String textField4;
    String textField5;
    
    //metrhths gia to an patithike to attach gia image, an den tha pernaei sta next question k end test default path sto s
    int imagePassed = 0;
  
    static ArrayList<CreateTest> list = new ArrayList<CreateTest>();
    
    public CreateTest() {
        initComponents();
        counterq++;
        
        if (counterq < 2) {
            Back.setVisible(false);
        }
        
        String q = Integer.toString(counterq);
        jLabel2.setText(q);
       
    }
    
    public CreateTest(String textfield) {
        initComponents();
        counterq++;
        
        if (counterq < 2) {
            Back.setVisible(false);
        }
        
        testname= textfield;
        
        String q = Integer.toString(counterq);
        jLabel2.setText(q);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel_image = new javax.swing.JLabel();
        jButton_attachimage = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EndTest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ερώτηση");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Επόμενη ερώτηση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_image.setText("icon");
        jLabel_image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton_attachimage.setText("Σύναψε φάκελο");
        jButton_attachimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_attachimageActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        EndTest.setText("Τέλος και Αποθήκευση");
        EndTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndTestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Δώσε αριθμό Σωστής Ερώτησης (1-4)");

        Back.setText("Προηγούμενη ερώτηση");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EndTest)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton_attachimage)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton_attachimage)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(EndTest)
                    .addComponent(Back))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Υπάρχουν κενά πεδία, συμπλήρωσε όλα τα πεδία");
        } else {
        
        this.dispose();
        textArea = jTextArea1.getText();
        textField1 = jTextField1.getText();
        textField2 = jTextField2.getText();
        textField3 = jTextField3.getText();
        textField4 = jTextField4.getText();
        textField5 = jTextField5.getText();
     
        list.add(this);
        CreateTest ct2 = new CreateTest();
        ct2.setVisible(true);
        ct2.setResizable(false);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_attachimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_attachimageActionPerformed
        // TODO add your handling code here
        
      
         JFileChooser chooser = new JFileChooser();
         chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE","jpeg","gif","png");
         chooser.addChoosableFileFilter(filter);
         int result = chooser.showSaveDialog(null);
         if (result == JFileChooser.APPROVE_OPTION) {
             File selectedFile = chooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             jLabel_image.setIcon(ResizeImage(path));
             s = path;
             System.out.print(s);
         } 
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
         imagePassed++;
        
    }//GEN-LAST:event_jButton_attachimageActionPerformed

    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void EndTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndTestActionPerformed
        // TODO add your handling code here:
      
        if (jTextArea1.getText().isEmpty() || jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Υπάρχουν κενά πεδία, συμπλήρωσε όλα τα πεδία");
        } else {
       
       this.dispose();
        textArea = jTextArea1.getText();
        textField1 = jTextField1.getText();
        textField2 = jTextField2.getText();
        textField3 = jTextField3.getText();
        textField4 = jTextField4.getText();
        textField5 = jTextField5.getText();
       
        list.add(this);
       
       for (int i=0; i<list.size(); i++) {
           int no = i +1;
           String tname = list.get(i).testname;
           String ta = list.get(i).textArea;
           String tf1 =  list.get(i).textField1;
           String tf2 = list.get(i).textField2;
           String tf3 = list.get(i).textField3;
           String tf4 = list.get(i).textField4;
           String tf5 = list.get(i).textField5;
           
             int ans = 0;
           ans = Integer.parseInt(tf5);
           
           
           try {
                if (list.get(i).imagePassed > 0) {
                    
               InputStream is = new FileInputStream(new File(list.get(i).s));
               theQuery4(tname,no,ta,tf1,tf2,tf3,tf4,ans, is);
                } else {
                    list.get(i).s = "C:"+"\\"+"Users"+"\\"+"anna"+"\\"+"Documents"+"\\"+"NetBeansProjects"+"\\"+"quiz"+"\\"+"src"+"\\"+"quiz"+"\\"+"test.jpg";
                    System.out.println(s);
                    InputStream is = new FileInputStream(new File(list.get(i).s));
                    theQuery4(tname,no,ta,tf1,tf2,tf3,tf4,ans, is);
                    
                }    
           } catch (FileNotFoundException ex) {
               Logger.getLogger(CreateTest.class.getName()).log(Level.SEVERE, null, ex);
           }
            }
        }
       
    }//GEN-LAST:event_EndTestActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        
        counterq -=2;
        list.remove(list.size()-1);
        
        
        this.dispose();
        
        if (counterq < 0) {
            CreateTest ct2 = new CreateTest(testname);
            ct2.setVisible(true);
            ct2.setResizable(false);
        } else {
            CreateTest ct2 = new CreateTest();
            ct2.setVisible(true);
            ct2.setResizable(false);
        }
        
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTest().setVisible(true);
            }
        });
    }
    
    public void queryUpdate2(String tname, int n, String t1, String rb1, String rb2, String rb3, String rb4, int ra) {
        
        Connection con = null;
        Statement st = null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            //String sql1 = "update question2 set texta = '"+t1+"',rbutton1 = '"+rb1+"',rbutton2 = '"+rb2+"',rbutton3 = '"+rb3+"',rbutton4 = '"+rb4+"',n_of_ran = '"+ra+"' where testname = '"+tname+"' and No = '"+n+"'";
            //String sql1 = "update question2 set texta = '"+t1+"',rbutton1 = '"+rb1+"',rbutton2 = '"+rb2+"',rbutton3 = '"+rb3+"',rbutton4 = '"+rb4+"',n_of_ran = '"+ra+"' where testname = '"+tname+"' and No = '"+n+"'";
            String sql = "UPDATE question2 SET texta=?, rbutton1=?, rbutton2=?, rbutton3=?, rbutton4=?, n_of_ran=? where testname=? and No=?";

            PreparedStatement ps = con.prepareStatement(sql);
         
            ps.setString(1, t1);
            ps.setString(2, rb1);
            ps.setString(3, rb2);
            ps.setString(4, rb3);
            ps.setString(5, rb4);
            ps.setInt(6, ra);
            ps.setString(7, tname);
            ps.setInt(8, n);
            ps.executeUpdate();
            ps.close();
             
        } catch (Exception e) {
            e.printStackTrace();
        }  
        
    }
    
    
    
    public void theQuery4(String tname, int n, String t1, String rb1, String rb2, String rb3, String rb4, int ra, InputStream is) {
        
        Connection con = null;
        
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            PreparedStatement ps = con.prepareStatement("insert into question2 (testname,No,texta,rbutton1,rbutton2,rbutton3,rbutton4,n_of_ran,image) values (?,?,?,?,?,?,?,?,?)");
            //InputStream is = new FileInputStream(new File(s));
            ps.setString(1, tname);
            ps.setInt(2, n);
            ps.setString(3, t1);
            ps.setString(4, rb1);
            ps.setString(5, rb2);
            ps.setString(6, rb3);
            ps.setString(7, rb4);
            ps.setInt(8, ra);
            ps.setBlob(9, is);
            ps.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Τα δεδομένα κατοχυρώθηκαν");
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }  
        
    }
    
    
    public void theQuery3(String tname, int n, String t1, String rb1, String rb2, String rb3, String rb4, int ra) {
        
        Connection con = null;
        Statement st = null;
        //String sql1 = "insert into question2 (testname,No,texta,textf1) values('"+tname+"','"+n+"','"+t1+"','"+t2+"')";
        //String sql1 = "insert into question2 (testname,No,texta,textf1,rbutton2) values('"+tname+"','"+n+"','"+t1+"','"+t2+"','"+rb2+"')";
        //String sql1 = "insert into question2 (testname,No,texta,rbutton1,rbutton2) values('"+tname+"','"+n+"','"+t1+"','"+rb1+"','"+rb2+"')"; 
        String sql1 = "insert into question2 (testname,No,texta,rbutton1,rbutton2,rbutton3,rbutton4,n_of_ran) values('"+tname+"','"+n+"','"+t1+"','"+rb1+"','"+rb2+"','"+rb3+"','"+rb4+"','"+ra+"')";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Τα δεδομένα κατοχυρώθηκαν");
            st.executeUpdate(sql1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Τα δεδομένα ΔΕΝ κατοχυρώθηκαν");
        }
    }
    
    public void queryUpdate(String tname, int n, String t1, String rb1, String rb2, String rb3, String rb4, int ra, InputStream is) {
       
        Connection con = null;
        
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            PreparedStatement ps = con.prepareStatement("update question2 set texta = ?,rbutton1 = ?,rbutton2 = ?,rbutton3 = ?,rbutton4 = ?,n_of_ran = ?,image = ? where testname = ? and No = ?");
            //InputStream is = new FileInputStream(new File(s));
            
            ps.setString(1, t1);
            ps.setString(2, rb1);
            ps.setString(3, rb2);
            ps.setString(4, rb3);
            ps.setString(5, rb4);
            ps.setInt(6, ra);
            ps.setBlob(7, is);
            ps.setString(8, tname);
            ps.setInt(9, n);
            ps.executeUpdate();
            ps.close();
            //JOptionPane.showMessageDialog(null, "Τα δεδομένα ανανεώθηκαν");
            
        } catch (Exception e) {
            e.printStackTrace();
        }   
    }
    
    public void theQuery() {
        Connection con = null;
        PreparedStatement ps = null;
        
        //Statement st = null;
        try{
            //con = DriverManager.getConnection("jdbc:mysql://localhost/testmaker1","root","1234");
            //st = con.createStatement();
            
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql:///testmaker1","root","1234");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            //ps = con.prepareStatement("insert into questions values (?,?,?)");
            //ps.setInt(1, counterq);
            //ps.setString(2, textArea);
            //ps.setString(3, textField1);
            ps = con.prepareStatement("insert into questions (no,texta,textf) values('"+counterq+"','"+textArea+"','"+textField1+"')");
            int i = ps.executeUpdate();
            if(i>0) {
                JOptionPane.showMessageDialog(null, "Τα δεδομένα κατοχυρώθηκαν");
            } else {
               JOptionPane.showMessageDialog(null, "Τα δεδομένα ΔΕΝ κατοχυρώθηκαν.."); 
            } 
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton EndTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_attachimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
