/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author anna
 */
public class NameTest extends javax.swing.JFrame {

    static int t_id;
    static byte[] im = null;
    /**
     * Creates new form NameTest
     */
    public NameTest() {
        initComponents();
        jSpinner1.setVisible(false);
        
         ItemHandler handler = new ItemHandler();
        jRadioButton1.addItemListener(handler);
        
        Role r = new Role();
        r.getBackgroundImage();
        im = r.im;
        ImageIcon image = new ImageIcon(im); 
        Image nim =  image.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel6.setIcon(image);
    }
    public NameTest(int id) {
        initComponents();
        jSpinner1.setVisible(false);
        jLabel3.setVisible(false);
        t_id = id;
        
        ItemHandler handler = new ItemHandler();
        jRadioButton1.addItemListener(handler);
        
        Role r = new Role();
        r.getBackgroundImage();
        im = r.im;
        ImageIcon image = new ImageIcon(im); 
        Image nim =  image.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel6.setIcon(image);
       
    }
    
    private class ItemHandler implements ItemListener {
        
        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getSource() == jRadioButton1) {
                jLabel3.setVisible(true);
                jSpinner1.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(573, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Τίτλος Τεστ:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 190, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 70, 389, 20);

        Submit.setText("Αποδοχή");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(350, 250, 90, 23);

        back.setText("Πίσω");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 260, 70, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Αρνητική βαθμολογία;");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 140, 14);

        jRadioButton1.setText("Ναι");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(260, 120, 60, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Αρνητικός βαθμός (0-2)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 140, 14);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 2.0d, 0.1d));
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(260, 160, 60, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Επιτρεπόμενες προσπάθειες:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 170, 14);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(260, 200, 60, 20);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 580, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        
        if(jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Δώσε όνομα στο τεστ");
        } else {
        
            if(checkIfTestExists(jTextField1.getText())) {
                JOptionPane.showMessageDialog(null, "Υπάρχει ήδη τεστ με αυτό το όνομα, διάλεξε άλλο όνομα");
            } else {
            
        this.dispose();
        
        double rate = round((Double)jSpinner1.getValue(),1);
        int allow_atts = (int) jSpinner2.getValue();
        
        CreateTest2 ct = new CreateTest2(jTextField1.getText(), t_id, rate, allow_atts);
        ct.setVisible(true);
        ct.setResizable(false);
        
        }
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Teacher t = new Teacher(t_id);
        t.setVisible(true);
        t.setResizable(false);
    }//GEN-LAST:event_backActionPerformed

    //kanw ton arithmo na xei tosa pshfia oso thesw to places
    public static double round(double value, int places) {
    if (places < 0) throw new IllegalArgumentException();

    long factor = (long) Math.pow(10, places);
    value = value * factor;
    long tmp = Math.round(value);
    return (double) tmp / factor;
}
    
    private boolean checkIfTestExists(String tn) {
        
        Connection con = null;
        PreparedStatement ps = null;
        String sql = "select * from test_teacher where testname= '" + tn + "'";
        //anti gia null ebala mia protash giati me null m petaei null exception sto if
        String tname="den uparxei auto to test sigoura";
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            
            while(rs.next()){
            
            tname = rs.getString("testname");
             
            }
                
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
                }
        if (tname.equals(jTextField1.getText()) ) {
        
            return true;
        } else {
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
