/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz; 

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author anna
 */
public class Role extends javax.swing.JFrame {

    
    static byte[] im = null;
    /**
     * Creates new form Role
     */
    public Role() {
        //αυτη η μεθοδος σε καθε frame δημιοργια τα buttons labels τις διαστασεις, ολα
        initComponents();
        getBackgroundImage();
        ImageIcon image = new ImageIcon(im); 
        Image nim =  image.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel3.setIcon(image);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        teacherLog = new javax.swing.JButton();
        studentLog = new javax.swing.JButton();
        signIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(589, 355));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Είσοδος ως:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 80, 251, 22);

        teacherLog.setText("Καθηγητής");
        teacherLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherLogActionPerformed(evt);
            }
        });
        getContentPane().add(teacherLog);
        teacherLog.setBounds(100, 140, 110, 23);

        studentLog.setText("Μαθητής");
        studentLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLogActionPerformed(evt);
            }
        });
        getContentPane().add(studentLog);
        studentLog.setBounds(100, 190, 110, 23);

        signIn.setText("Sign in");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        getContentPane().add(signIn);
        signIn.setBounds(460, 60, 90, 23);

        jLabel3.setMaximumSize(new java.awt.Dimension(1900, 1200));
        jLabel3.setMinimumSize(new java.awt.Dimension(1900, 1200));
        jLabel3.setPreferredSize(new java.awt.Dimension(1900, 700));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherLogActionPerformed
        
        this.dispose();
        TeachLogIn lg = new TeachLogIn();
        lg.setVisible(true);
        lg.setResizable(false);
    }//GEN-LAST:event_teacherLogActionPerformed

    private void studentLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLogActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        //Student st = new Student();
        //st.setVisible(true);
        StudentLogIn sl = new StudentLogIn();
        sl.setVisible(true);
        sl.setResizable(false);
        
    }//GEN-LAST:event_studentLogActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SignIn si = new SignIn();
        si.setVisible(true);
        si.setResizable(false);
    }//GEN-LAST:event_signInActionPerformed

     public void getBackgroundImage() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select background from images";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            im = rs.getBytes("background");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
    }
    /**
     * @param args the command line arguments
     */
    //ΔΕΝ χρησιμοποιειται....σε καθε frame το φερνει αυτοματα
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Role().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton signIn;
    private javax.swing.JButton studentLog;
    private javax.swing.JButton teacherLog;
    // End of variables declaration//GEN-END:variables
}
