/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author anna
 */
public class SignIn extends javax.swing.JFrame {
    
    static byte[] im = null;
    
    String fname;
    String lname;
    String username;
    String password;
    String AM;
    

    /**
     * Creates new form SignIn
     */
    //αρχικα εχω notVisible τα πεδια του ΑΜ κ περναω σαν παραμετρο το object της itemHandler class
    public SignIn() {
        initComponents();
        jLabel6.setVisible(false);
        jTextField4.setVisible(false);
        
         ItemHandler handler = new ItemHandler();
        jRadioButton2.addItemListener(handler);
        jRadioButton1.addItemListener(handler);
        
        Role r = new Role();
        r.getBackgroundImage();
        im = r.im;
        ImageIcon image = new ImageIcon(im); 
        Image nim =  image.getImage().getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel7.setIcon(image);
    }
    
    // σ αυτη τη κλαση οταν πατηθει το 1ο radiobutton δεν φαινονται τα πεδια του ΑΜ κ οταν πατηθει το 2ο φαινονται
     private class ItemHandler implements ItemListener {
        
        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getSource() == jRadioButton2) {
                 jLabel6.setVisible(true);
                 jTextField4.setVisible(true);
            }
            if (event.getSource() == jRadioButton1) {
                 jLabel6.setVisible(false);
                 jTextField4.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(453, 400));
        setPreferredSize(new java.awt.Dimension(453, 400));
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 90, 209, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 130, 209, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Όνομα");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 93, 100, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Επίθετο");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 131, 100, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(32, 172, 110, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 170, 209, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(32, 207, 110, 14);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Καθηγητής");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(40, 242, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Μαθητής");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(194, 242, 100, 23);

        submit.setText("Αποδοχή");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(244, 341, 100, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Λεπτομέρειες εγγραφής");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(98, 23, 240, 22);

        exit.setText("Έξοδος");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(76, 341, 90, 23);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(160, 210, 209, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 293, 50, 14);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(137, 290, 170, 20);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 700, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //τσεκαρω ποιο radiobutton πατηθηκε κ αναλογα περναω στο αντιστοιχο table (student,teacher) ta sστοιχεια. Και 
    //validation οτι δεν υπαρχουν κενα πεδια
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jPasswordField1.getText().isEmpty() ||(!jRadioButton1.isSelected() && !jRadioButton2.isSelected())) {
            JOptionPane.showMessageDialog(null, "Υπάρχουν κενά πεδία, συμπλήρωσε όλα τα πεδία");
          
        }
        else {
                 
            fname = jTextField1.getText().toString();
            lname = jTextField2.getText().toString();
            username = jTextField3.getText().toString();
            password = jPasswordField1.getText().toString();
            AM = jTextField4.getText().toString();
            
            if (jRadioButton1.isSelected()) {
                Connection con = null;
                Statement st = null;
                String sql1 = "insert into teacher (fname,lname,username,password) values('"+fname+"','"+lname+"','"+username+"','"+password+"')";
                
                try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            st.executeUpdate(sql1);
            JOptionPane.showMessageDialog(null, "Τα δεδομένα κατοχυρώθηκαν");
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Τα δεδομένα ΔΕΝ κατοχυρώθηκαν");
                 }
            } else if (jRadioButton2.isSelected()) {
                if (jTextField4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Δώσε το AM σου");
                } else {
                  Connection con = null;
                Statement st = null;
                String sql1 = "insert into student (fname,lname,username,password,AM) values('"+fname+"','"+lname+"','"+username+"','"+password+"','"+AM+"')";
                
                try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            st.executeUpdate(sql1);
            JOptionPane.showMessageDialog(null, "Τα δεδομένα κατοχυρώθηκαν");
            this.dispose();
            Role r = new Role();
            r.setVisible(true);
            r.setResizable(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Τα δεδομένα ΔΕΝ κατοχυρώθηκαν");
                 }
            }
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Role r = new Role();
        r.setVisible(true);
        r.setResizable(false);
    }//GEN-LAST:event_exitActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
