/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static quiz.ViewTest.img;

/**
 *
 * @author anna
 */
public class Student extends javax.swing.JFrame {

    static byte[] img = null;
    static int s_id;
    static String testname;
    static String testname2;
    int atts = 0;
    int atts2 = 0;
    
    int attempt;
    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        Role r = new Role();
        r.getBackgroundImage();
        img = r.im;
        ImageIcon image2 = new ImageIcon(img); 
        Image nim2 =  image2.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        image2 = new ImageIcon(nim2);
        jLabel4.setIcon(image2);
        
        //jComboBox3.setVisible(false);
        Fillcombo();
        fillCombo2();
        
         ItemHandler handler = new ItemHandler();
        jComboBox2.addItemListener(handler);
    }
    public Student(int id) {
        initComponents();
        Role r = new Role();
        r.getBackgroundImage();
        img = r.im;
        ImageIcon image2 = new ImageIcon(img); 
        Image nim2 =  image2.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        image2 = new ImageIcon(nim2);
        jLabel4.setIcon(image2);
        //jComboBox3.setVisible(false);
        s_id = id;
        Fillcombo();
        fillCombo2();
        
        
        ItemHandler handler = new ItemHandler();
        jComboBox2.addItemListener(handler);
    }

    
    private class ItemHandler implements ItemListener {
        
        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getSource() == jComboBox2) {
                 jComboBox3.removeAllItems();
                testname2 = jComboBox2.getSelectedItem().toString();
                fillCombo3();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        solve = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        viewTest = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 409));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Επίλυση Τεστ:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 50, 126, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL TESTS" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 100, 90, 20);

        solve.setText("Λύση Τεστ");
        solve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveActionPerformed(evt);
            }
        });
        getContentPane().add(solve);
        solve.setBounds(250, 100, 100, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL TESTS" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(50, 230, 90, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATTEMPTS" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(170, 230, 90, 20);

        viewTest.setText("Προβολή Τεστ");
        viewTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTestActionPerformed(evt);
            }
        });
        getContentPane().add(viewTest);
        viewTest.setBounds(290, 230, 140, 23);

        exit.setText("Έξοδος");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(200, 330, 80, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Προβολή Απαντημένων Τεστ:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 310, 22);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 640, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveActionPerformed
        // TODO add your handling code here:
     
        if ( jComboBox1.getSelectedItem().toString() == "ALL TESTS") {
             JOptionPane.showMessageDialog(null, "Choose a Test");
        } else {
        //metrhths an uparxei to onoma tou test sto table me ta solved k posses fores(posa attempts)
        int count = 0;
        ArrayList<String> n = new ArrayList<String>();
            
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select testname from test_student where id_student=" + s_id + "";
        
        testname = jComboBox1.getSelectedItem().toString();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Connected");
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            String name = rs.getString("testname");
            n.add(name); 
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
        
            for (int i=0; i<n.size(); i++){
                if (n.get(i).equals(testname)) {
                    count++;    
                }  
            }
        
            allowedAttempts();
        if (count>=atts) {
            JOptionPane.showMessageDialog(null, "Έχεις λύσει ήδη το τεστ, δεν έχεις αλλη ελεύθερη προσπάθεια.."); 
        } else {
        this.dispose();
        //ShowQuestion sq = new ShowQuestion(nameOfTest);
        ShowQuestion2 sq = new ShowQuestion2(testname, s_id);
        sq.setVisible(true);
        sq.setResizable(false);
        }
        }
    }//GEN-LAST:event_solveActionPerformed

    
    private void viewTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTestActionPerformed
        // TODO add your handling code here:
        

        if (jComboBox2.getSelectedItem().toString() == "ALL TESTS" || jComboBox3.getSelectedItem().toString() == "ATTEMPTS") {
             JOptionPane.showMessageDialog(null, "Διάλεξε τεστ");
        } else {
            
            if (checkAttemptsToShowTest()) {
            //testname2 = jComboBox2.getSelectedItem().toString();
            String a = jComboBox3.getSelectedItem().toString();
            attempt = Integer.parseInt(a);
            
            this.dispose();
            String r = "student";
            StudentViewTest svt = new StudentViewTest(s_id,testname2, attempt, r);
            svt.setVisible(true);
            svt.setResizable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Υπάρχουν και άλλες ελεύθερες προσπάθειες για το τεστ, ακόμα δεν επιτρέπεται αυτή η ενέργεια");
            }
        }
    }//GEN-LAST:event_viewTestActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        s_id = 0;
        testname = null;
        testname2 = null;
        this.dispose();
        StudentLogIn stl = new StudentLogIn();
        stl.setVisible(true);
        stl.setResizable(false);
    }//GEN-LAST:event_exitActionPerformed

    public void Fillcombo(){
        
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        //String sql = "select distinct testname from question2";
        String sql = "select distinct testname from test_teacher where published='1'";
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Connected");
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String name = rs.getString("testname");
                jComboBox1.addItem(name);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
    }
    
    public void fillCombo2() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select distinct testname from test_student where id_student='" + s_id + "'";
        //String sql = "select * from question2";
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Connected");
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String name = rs.getString("testname");
                jComboBox2.addItem(name);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
    }
       
    public void fillCombo3() {
         Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select attempt_no from test_student where id_student='" + s_id + "' and testname='" + testname2 + "'";
        //String sql = "select * from question2";
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Connected");
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String attempts = rs.getString("attempt_no");
                jComboBox3.addItem(attempts);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
    }
    
    private void allowedAttempts() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select * from test_teacher where testname= '" + testname + "'";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                atts =  rs.getInt("allow_attempts");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
        
    }
    private void allowedAttempts2() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String tname = jComboBox2.getSelectedItem().toString();
        String sql = "select * from test_teacher where testname= '" + tname + "'";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                atts2 =  rs.getInt("allow_attempts");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
        
    }
    
    private boolean checkAttemptsToShowTest() {
        //metrhths an uparxei to onoma tou test sto table me ta solved k posses fores(posa attempts)
        int count = 0;
        ArrayList<String> n = new ArrayList<String>();
            
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select testname from test_student where id_student=" + s_id + "";
        
        String tname = jComboBox2.getSelectedItem().toString();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            String name = rs.getString("testname");
            n.add(name); 
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ΔΕΝ έιναι σε σύνδεση με τη βάση");
        }
        
            for (int i=0; i<n.size(); i++){
                if (n.get(i).equals(tname)) {
                    count++;    
                }  
            }
        
            allowedAttempts2();
        if (count>=atts2) {
            return true; 
        } else {
            return false;
    }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton solve;
    private javax.swing.JButton viewTest;
    // End of variables declaration//GEN-END:variables
}
