/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author anna
 */
public class TeacherChoice extends javax.swing.JFrame {

    static byte[] im = null;
    static int t_id;
    /**
     * Creates new form TeacherChoice
     */
    public TeacherChoice() {
        initComponents();
        fillCombo();
        
        Role r = new Role();
        r.getBackgroundImage();
        im = r.im;
        ImageIcon image = new ImageIcon(im); 
        Image nim =  image.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel2.setIcon(image);
    }
     public TeacherChoice(int id) {
        initComponents();
        t_id = id;
        fillCombo();
        
        Role r = new Role();
        r.getBackgroundImage();
        im = r.im;
        ImageIcon image = new ImageIcon(im); 
        Image nim =  image.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        image = new ImageIcon(nim);
        jLabel2.setIcon(image);
    }
    
    
    void fillCombo(){
        
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        //String sql = "select distinct testname from question2";
        String sql = "select distinct testname from question2 where id_teacher = " + t_id + "";
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            //JOptionPane.showMessageDialog(null, "Connected");
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String name = rs.getString("testname");
                jComboBox1.addItem(name);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Δεν υπάρχει σύνδεση με τη βάση");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        chooseTest = new javax.swing.JButton();
        deleteTest = new javax.swing.JButton();
        deleteQuestion = new javax.swing.JButton();
        viewTest = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(582, 365));
        setPreferredSize(new java.awt.Dimension(582, 365));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Επιλογή τεστ:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 180, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL TESTS" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 130, 90, 20);

        chooseTest.setText("Επεξεργασία / Προσθήκη Ερώτησης");
        chooseTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTestActionPerformed(evt);
            }
        });
        getContentPane().add(chooseTest);
        chooseTest.setBounds(330, 120, 240, 23);

        deleteTest.setText("Διαγραφή Τεστ");
        deleteTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTestActionPerformed(evt);
            }
        });
        getContentPane().add(deleteTest);
        deleteTest.setBounds(330, 200, 240, 23);

        deleteQuestion.setText("Διαγραφή Ερώτησης");
        deleteQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(deleteQuestion);
        deleteQuestion.setBounds(330, 160, 240, 23);

        viewTest.setText("Προβολή Τεστ");
        viewTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTestActionPerformed(evt);
            }
        });
        getContentPane().add(viewTest);
        viewTest.setBounds(330, 80, 240, 23);

        back.setText("Πίσω");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 270, 80, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Επιλογή ενέργειας:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 40, 190, 22);

        jLabel2.setMaximumSize(new java.awt.Dimension(1900, 1200));
        jLabel2.setMinimumSize(new java.awt.Dimension(1900, 1200));
        jLabel2.setPreferredSize(new java.awt.Dimension(1900, 700));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTestActionPerformed
        // TODO add your handling code here:
        
        if ( jComboBox1.getSelectedItem().toString() == "ALL TESTS") {
             JOptionPane.showMessageDialog(null, "Διάλεξε τεστ");
        } else {
        this.dispose();
        ChangeNegRate cnr = new ChangeNegRate(jComboBox1.getSelectedItem().toString(),t_id);
        cnr.setVisible(true);
        cnr.setResizable(false);
        //TeacherViewTest tvt = new TeacherViewTest(jComboBox1.getSelectedItem().toString(), t_id);
        //tvt.setVisible(true);
        }
    }//GEN-LAST:event_chooseTestActionPerformed

    private void deleteTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTestActionPerformed
        // TODO add your handling code here:
        if ( jComboBox1.getSelectedItem().toString() == "ALL TESTS") {
             JOptionPane.showMessageDialog(null, "Διάλεξε τεστ");
        } else {
        
        String tname = jComboBox1.getSelectedItem().toString();
       String sql = "DELETE FROM question2 WHERE testname='"+tname+"'";
       String sql2 = "DELETE FROM test_teacher WHERE testname='"+tname+"'";
               
       Connection con = null;
        Statement st = null;
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            st.executeUpdate(sql);
            //JOptionPane.showMessageDialog(null, "Το τεστ διαγράφηκε");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Το τεστ ΔΕΝ διαγράφηκε");
        }
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?zeroDateTimeBehavior=convertToNull","root","");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testmaker?useUnicode=true&characterEncoding=utf-8","root","");
            st = con.createStatement();
            st.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null, "Το τεστ διαγράφηκε");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Το τεστ ΔΕΝ διαγράφηκε");
        }
        
       
         this.dispose();
         TeacherChoice tc = new TeacherChoice();
         tc.setVisible(true);
         tc.setResizable(false);
        }
    }//GEN-LAST:event_deleteTestActionPerformed

    private void deleteQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteQuestionActionPerformed
        // TODO add your handling code here:
        
        if ( jComboBox1.getSelectedItem().toString() == "ALL TESTS") {
             JOptionPane.showMessageDialog(null, "Διάλεξε τεστ");
        } else {
            this.dispose();
         DeleteQuestion dq = new  DeleteQuestion(jComboBox1.getSelectedItem().toString());
         dq.setVisible(true);
         dq.setResizable(false);
        }
    }//GEN-LAST:event_deleteQuestionActionPerformed

    private void viewTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTestActionPerformed
        // TODO add your handling code here:
         if ( jComboBox1.getSelectedItem().toString() == "ALL TESTS") {
             JOptionPane.showMessageDialog(null, "Διάλεξε τεστ");
        } else {
        this.dispose();
        ViewTest vt = new ViewTest(t_id,jComboBox1.getSelectedItem().toString());
        vt.setVisible(true);
        vt.setResizable(false);
         }
    }//GEN-LAST:event_viewTestActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Teacher t = new Teacher();
        t.setVisible(true);
        t.setResizable(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton chooseTest;
    private javax.swing.JButton deleteQuestion;
    private javax.swing.JButton deleteTest;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton viewTest;
    // End of variables declaration//GEN-END:variables
}
